### ISSUE TITLE
Use reverse engineering for functions comparison

### ISSUE THREAD

**Issue by Konard** [linksplatform/Delegates#13]
https://tproger.ru/translations/main-is-usually-a-function-so-then-when-is-it-not/
![image](https://user-images.githubusercontent.com/1431904/117839976-67183900-b284-11eb-8415-4adba3d981db.png)
https://godbolt.org/z/hc5Gq1zna
![image](https://user-images.githubusercontent.com/1431904/117839984-6a132980-b284-11eb-8f49-9c3073820b6f.png)

![Screenshot_20210511_182132](https://user-images.githubusercontent.com/1431904/117841428-ba3ebb80-b285-11eb-9339-bb636e5e7ff1.png)

For example, we can use `c3` / `195` (`ret`) as marker of the function end.
That means we can read up to the end of the function to compare its code to another function.

Looks like we can use this hack (or other) until a better solution is proposed by C++ standard.

**Comment by uselessgoddess** [comment]
Check this example
https://godbolt.org/z/T7z689E4P

**Comment by Konard** [comment]
Optimizations are ok. Both functions do exactly the same sequence of operations.

**Comment by uselessgoddess** [comment]
But without optimization this two different functions

**Comment by Konard** [comment]
> But without optimization this two different functions

We should write about of all side effects of such comparison in the documentation.

**Comment by Konard** [comment]
https://zydis.re can be used for that task.
We can use it as an optional dependency, if user includes it is supported.

**Comment by Konard** [comment]
No need to solve this issue, because https://github.com/linksplatform/Delegates/issues/24 is a much better solution.
