### ISSUE TITLE
Call of overloaded is ambiguous

### ISSUE THREAD

**Issue by uselessgoddess** [linksplatform/Delegates#14]
See this example 
`Platform::Delegate` has  the same constructors
```cpp
struct test
{
    test(void(*func)()) {}
    test(std::function<void()> func) {}
};

int main()
{
    test{[](){}}; // error `overloaded is ambiguous`
    test{std::function{[](){}}};
}
```
Therefore, we can't pass lambda expression to constructor

**Comment by Konard** [comment]
Hm...

**Comment by uselessgoddess** [comment]
Hm. 
`lambda` convertible to `std::function` and 
`lambda` convertible to `std::function`, but `lambda` is not same `pointer-function`
Therefore, there is an ambiguity. It can be passed to one of two constructors and each of them will call `static_cast`

Might use:
```cpp
int main()
{
    test{static_cast<void(*)()>([](){})};
    test{std::function{[](){}}};
}
```

**Comment by Konard** [comment]
Did you mean `lambda` convertible to `void(*)()`?

**Comment by uselessgoddess** [comment]
Lambda have implicit cast to void(*)()
And std::function have implicit constructor from lambda
